- name: 📂 FTP Deploy
  uses: SamKiriles/ftp-deploy@v2 # Or whichever FTP action you are using
  with:
    server: ${{ secrets.FTP_SERVER }}
    username: ${{ secrets.FTP_USERNAME }}
    password: ${{ secrets.FTP_PASSWORD }}
    # local-dir: ./dist/ (Optional: specify the folder to upload)
